import "@/styles/globals.css";
import type { Metadata } from "next";
import { ThemeProvider } from "@/components/utils/theme-provider";
import { cn } from "@/lib/utils";
import { fontSpaceGrotesk } from "@/lib/fonts";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          `min-h-screen bg-background ${fontSpaceGrotesk.className} font-sans antialiased`
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <NextTopLoader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
